name: Spec Resource Models Generation Regression Test

on:
  workflow_run:
    workflows: ["Test"]
    branches: ["main"]
    types: ["completed"]

permissions:
  contents: read

jobs:
  validate-generated-models:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        spec_version: ["r4", "r5"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Cache spec StructureDefinition bundle
        id: spec-download
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-spec-download-${{ hashFiles('./spec/${{ matrix.spec_version }}.bundle.checksumfile') }}
          path:
            - ./spec/fhir.types.json
            - ./spec/fhir.resources.json
      - name: Download spec StructureDefinition bundle
        if: steps.spec-download.outputs.cache-hit != 'true'
        run: |
          cd ./spec/
          bash download_spec_bundle.sh ${{ matrix.spec_version }}
          cd ..
      - name: Build resource models from the spec StructureDefinition bundle
        run: |
          poetry run typegen --from-bundles spec/fhir.types.json --from-bundles spec/fhir.resources.json --outfile generated/resources.py
      - name: Typecheck generated resource models
        run: poetry run mypy generated/resources.py
